const DEFAULT_DATA = {
  title: 'Find Your Career',
  description: 'This questionnaire helps you discover which career best matches your interests, strengths, and working style. There are no right or wrong answers. Please answer honestly.',
  questions: [
    'I enjoy communicating with new people.', 'I like helping customers solve problems.', 'I enjoy speaking English with foreigners.', 'I enjoy writing articles, captions, or stories.', 'I enjoy creating videos or social media content.', 'I enjoy organizing events and coordinating with others.', 'I enjoy planning and organizing my work.', 'I enjoy analyzing information before making decisions.', 'I like working in an office environment.', 'I enjoy traveling or working in different places.', 'I enjoy persuading people to buy products or services.', 'I enjoy negotiating with people.', 'I can stay calm when facing difficult customers.', 'I enjoy translating between Thai and English.', 'I enjoy learning new digital tools and AI applications.'
  ],
  careers: [
    ['Customer Relations',[1,2,13],'You enjoy connecting with people and calmly helping them solve problems.','Customer service, relationship management, call centers'],
    ['Public Relations',[1,3,6],'You are comfortable communicating, coordinating, and representing an organization.','PR agencies, communications teams, event companies'],
    ['Airline & Hospitality',[2,3,10,13],'You may thrive in service-oriented work with people from diverse backgrounds.','Airlines, hotels, tourism, guest relations'],
    ['Administration & Secretary',[7,8,9],'Your organized, detail-aware work style is a strong foundation for smooth operations.','Office administration, executive support, operations'],
    ['Marketing & Sales',[11,12,1],'You enjoy persuading, building rapport, and turning conversations into opportunity.','Sales, brand marketing, business development'],
    ['International Business',[3,8,12,10],'You combine global curiosity, analysis, negotiation, and adaptability.','Import/export, international sales, procurement'],
    ['Content Writer & Creator',[4,5,15],'You have an expressive side and enjoy turning ideas into engaging digital content.','Content marketing, social media, copywriting'],
    ['Translator',[3,14,4],'You enjoy bridging languages and expressing meaning clearly across cultures.','Translation, localization, bilingual content']
  ].map(([name,questions,description,examples])=>({name,questions,description,examples})),
  reflection: ['Does the result match your expectation?', 'Which career do you want to explore?', 'Which skills do you still need to improve?', 'Which company would you like to apply for?']
};
let data = JSON.parse(localStorage.getItem('careerCompassData') || 'null') || structuredClone(DEFAULT_DATA);
let index = 0, answers = [];
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function show(id){ $$('.panel').forEach(x=>x.classList.remove('active')); $(id).classList.add('active'); window.scrollTo({top:0,behavior:'smooth'}); }
function applySurveyIdentity(){$('#welcomeTitle').textContent=data.title || 'Find the path that fits you'; $('#welcomeCopy').textContent=data.description || 'A short survey to discover careers that align with your interests, strengths, and working style.'; document.title=data.title || 'Career Compass';}
function renderQuestion(){const q=data.questions[index]; $('#sectionLabel').textContent=`SECTION 1 / 1`;$('#progressLabel').textContent=`${index+1} / ${data.questions.length}`;$('#progressBar').style.width=`${((index+1)/data.questions.length)*100}%`;$('#questionText').textContent=q;$('#backButton').style.visibility=index?'visible':'hidden';$('#nextButton').querySelector('span').textContent=index===data.questions.length-1?'See results':'Next'; const labels=['Strongly disagree','Disagree','Neutral','Agree','Strongly agree']; $('#scale').innerHTML=labels.map((label,n)=>`<button class="scale-option ${answers[index]===n+1?'selected':''}" type="button" role="radio" aria-checked="${answers[index]===n+1}" data-value="${n+1}">${n+1}<small>${label}</small></button>`).join(''); $$('.scale-option').forEach(b=>b.onclick=()=>{answers[index]=+b.dataset.value;renderQuestion();});}
function scores(){return data.careers.map(c=>({career:c,score:c.questions.reduce((sum,n)=>sum+(answers[n-1]||0),0),max:c.questions.length*5})).sort((a,b)=>b.score-a.score)}
function renderResults(){const ranked=scores(), top=ranked[0], percentage=Math.round(top.score/top.max*100);$('#resultIntro').textContent='Your strongest match reflects what you enjoy and how you work.';$('#topResult').innerHTML=`<span class="result-badge">BEST CAREER MATCH</span><h2>${top.career.name}</h2><p>${top.career.description}</p><p class="score">${percentage}% MATCH</p><p class="examples">Explore: ${top.career.examples}</p>`;$('#reflectionList').innerHTML=data.reflection.map(x=>`<li>${x}</li>`).join('');show('#results');}
function questionEditor(){const root=$('#questionsEditor'),t=$('#questionTemplate');root.innerHTML=''; data.questions.forEach((question,i)=>{const item=t.content.cloneNode(true);item.querySelector('input').value=question;item.querySelector('input').oninput=e=>data.questions[i]=e.target.value;item.querySelector('button').onclick=()=>{data.questions.splice(i,1);questionEditor()};root.append(item);});}
function careerEditor(){const root=$('#careersEditor'),t=$('#careerTemplate');root.innerHTML='';data.careers.forEach((career,i)=>{const item=t.content.cloneNode(true),el=item.querySelector('.career-editor');el.querySelector('.career-name').value=career.name;el.querySelector('.career-questions').value=career.questions.join(', ');el.querySelector('.career-description').value=career.description;el.querySelector('.career-examples').value=career.examples;el.querySelector('.career-name').oninput=e=>career.name=e.target.value;el.querySelector('.career-questions').oninput=e=>career.questions=e.target.value.split(',').map(x=>+x.trim()).filter(Boolean);el.querySelector('.career-description').oninput=e=>career.description=e.target.value;el.querySelector('.career-examples').oninput=e=>career.examples=e.target.value;el.querySelector('.remove-button').onclick=()=>{data.careers.splice(i,1);careerEditor()};root.append(item);});}
function openSettings(){data=structuredClone(data);$('#surveyTitle').value=data.title;$('#surveyDescription').value=data.description;questionEditor();careerEditor();$('#settingsDialog').showModal();}
$('#startButton').onclick=()=>{index=0;answers=[];renderQuestion();show('#quiz')};$('#nextButton').onclick=()=>{if(!answers[index])return; if(index<data.questions.length-1){index++;renderQuestion()}else renderResults()};$('#backButton').onclick=()=>{if(index){index--;renderQuestion()}};$('#restartButton').onclick=()=>show('#welcome');$('#printButton').onclick=()=>window.print();$('#settingsButton').onclick=openSettings;
$$('.tab').forEach(tab=>tab.onclick=()=>{$$('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`#${tab.dataset.tab}Tab`).classList.add('active')});$('#addQuestionButton').onclick=()=>{data.questions.push('New question');questionEditor()};$('#addCareerButton').onclick=()=>{data.careers.push({name:'New career',questions:[1],description:'Describe why this career could fit.',examples:'Add examples'});careerEditor()};$('#saveSettings').onclick=()=>{data.title=$('#surveyTitle').value.trim()||DEFAULT_DATA.title;data.description=$('#surveyDescription').value.trim();data.questions=data.questions.filter(Boolean);localStorage.setItem('careerCompassData',JSON.stringify(data));$('#settingsDialog').close();applySurveyIdentity();};$('#cancelSettings').onclick=()=>$('#settingsDialog').close();$('#exportButton').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='career-compass-settings.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!Array.isArray(imported.questions)||!Array.isArray(imported.careers))throw Error();data=imported;$('#surveyTitle').value=data.title||'';$('#surveyDescription').value=data.description||'';questionEditor();careerEditor()}catch{alert('This file does not contain valid survey settings.')}};reader.readAsText(file)};$('#resetButton').onclick=()=>{if(confirm('Restore all questions and career matches to the default settings?')){data=structuredClone(DEFAULT_DATA);$('#surveyTitle').value=data.title;$('#surveyDescription').value=data.description;questionEditor();careerEditor()}};applySurveyIdentity();
